name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'images/**'        
  pull_request:
    branches: [ main ]    
    paths-ignore:
    - 'README.md'
    - 'images/**'    

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      registry: 
        image: registry:2
        ports:
          - 5000:5000
    env:
      ContainerAzure__RegistryName: ${{ secrets.AZURE_REGISTRYNAME }}
      ContainerAzure__Username: ${{ secrets.AZURE_REGISTRYUSERNAME }}
      ContainerAzure__Password: ${{ secrets.AZURE_REGISTRYPASSWORD }}
      KubernetesAzure__KubeConfig: ${{ secrets.AZURE_KUBECONFIG }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Install dependencies
      run: dotnet restore MLOps.NET.sln
    - name: Build
      run: dotnet build MLOps.NET.sln --configuration Release --no-restore
    - name: UnitTests
      run: dotnet test MLOps.NET.sln --configuration Release --no-restore --no-build --filter TestCategory=UnitTests      
    - name: IntegrationTests
      run: dotnet test MLOps.NET.sln --configuration Release --no-restore --no-build --filter TestCategory=Integration            
    - name: Pack
      run: dotnet pack MLOps.NET.sln --configuration Release --no-build -o .
    - name: Publish packages as artifact
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: '*.nupkg'
    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'pull_request' }}
      run: dotnet nuget push **/*.nupkg --skip-duplicate --no-symbols true
    
