name: Integration Tests (MLOps.NET.Azure)

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'images/**'        
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
    - 'images/**'        

jobs:
  integration-tests-azure:
    runs-on: ubuntu-latest

    services:
      registry: 
        image: registry:2
        ports:
          - 5000:5000
      azure: 
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env: 
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    - name: Install dependencies
      run: dotnet restore MLOps.NET.sln
    - name: Build
      run: dotnet build MLOps.NET.sln --configuration Release --no-restore 
    - name: Tests
      run: dotnet test MLOps.NET.sln --configuration Release --no-restore --no-build --filter TestCategory=IntegrationTestsAzure            

    
